feat: Consolidate all in interfaces (Debian)
michaelrigart/ansible-role-interfaces pull request #133
Opened 2022-09-08 10:25 UTC by jbe-dw

This PR is a proposal for #132

2022-09-08 10:32 UTC, jbe-dw commented
This would put all in interfaces file with each config separated with a distinct comment

2022-10-04 08:52 UTC, markgoddard requested changes

2022-10-04 08:52 UTC, markgoddard commented on tasks/debian.yml
> +- name: Debian | Ensure lo single configuration file
Needs to go after L63

2022-10-04 08:52 UTC, markgoddard commented on templates/bond_slave_Debian.j2
> +{% if ansible_distribution_major_version|int < 11 %}
`ansible_facts.distribution_major_version`

2022-10-06 15:31 UTC, jbe-dw commented on templates/bond_slave_Debian.j2
> +{% if ansible_distribution_major_version|int < 11 %}
done

2022-10-06 15:32 UTC, jbe-dw commented
Thanks for the review

2022-11-29 09:41 UTC, markgoddard approved these changes

2022-11-29 09:41 UTC, merged